### ISSUE TITLE
Double quotes are introduced in the taxa names

### ISSUE THREAD

**Issue by apcamargo** [genomewalker/collapse-gtdb-tree#1]
`collapse-gtdb-tree` introduces double quotes to taxa names in the Newick files, which can cause some troubles downstream. For instance:

```
("o__GWB1-36-13":0.63259,"o__UBA6919":0.49676)
```

The original tree file doesn't use double quotes.

**Comment by genomewalker** [comment]
Hi @apcamargo 
tomorrow I will add an option when [writing](https://github.com/genomewalker/collapse-gtdb-tree/blob/main/collapse_gtdb_tree/__main__.py#L60) the collapsed tree to use quotes or not.

Cheers
Antonio

**Comment by apcamargo** [comment]
Thank you!

**Comment by genomewalker** [comment]
Hi @apcamargo 
the new release has a new option called `--quoted-names` that adds quotes to the names. Now by default there a no quoted names. Let me know if you find any issues.

Cheers

**Comment by apcamargo** [comment]
Thank you, Antonio!
